[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "yarn build:app:docker"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
[environments.production.variables]
NODE_ENV = "production"
VITE_APP_PERSISTENT_ROOMS = "true"
VITE_APP_EDUCATIONAL_MODE = "true"
VITE_APP_DEBUG = "false"
RAILWAY_WEBSOCKET_URL = "${{websocket.RAILWAY_PUBLIC_DOMAIN}}"

[environments.production.services]
[environments.production.services.postgres]
type = "postgresql"
version = "15"

[environments.production.services.websocket]
type = "web"
buildCommand = "cd excalidraw-room && npm install && npm run build"
startCommand = "cd excalidraw-room && npm start"
port = 3002

[environments.production.services.websocket.variables]
NODE_ENV = "production"
PORT = "3002"
CORS_ORIGIN = "*"